### ISSUE TITLE
tweet_count_rel_duration_function

### ISSUE THREAD

**Issue by marinayxh** [dsi-principles-prog/midterm-marinayxh#1]
This functoin is used for linking the time duration, which is the time period that between the date of a user created the account and the date of a user's last action with this account, and any variable that we want, such as the tweet counts or the retweet counts. 

The function takes data frame and the variable that we are interested in, then grouped by time duration. Relative questions can be something like "how often has a user posts tweets during the entire time of using twitter?". The output could be 0, otherwise, it is positive. Use the data frame "new_gender_class".

inputs for function: df, var

new variable named: tweet_count_rel_duration

note: 
var needed to be scaled
do not forget to ungroup
var could be something other than "tweet_count", however, suggest you use this one
the new variable "time duration" is already created in the 10-import file
this should be just few lines; think it simply.

**Comment by waittim** [comment]
answered
